-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.personaldetails
(
    ssn character varying(20),
    name character varying(40) NOT NULL,
    honorific character varying(10),
    highestdegree character varying(20),
    email character varying(40),
    phonenumber character varying(20),
    birthdate date,
    perstreet character varying(50),
    percity character varying(30),
    perstate character varying(10),
    perzip character varying(10),
    PRIMARY KEY (ssn)
);

CREATE TABLE IF NOT EXISTS public.departments
(
    departmentid serial,
    departmentname character varying(20) NOT NULL,
    departmentdescription text,
    PRIMARY KEY (departmentid),
    UNIQUE (departmentname)
);

CREATE TABLE IF NOT EXISTS public.jobtitles
(
    jobtitleid serial,
    jobtitle character varying(40) NOT NULL,
    PRIMARY KEY (jobtitleid),
    UNIQUE (jobtitle)
);

CREATE TABLE IF NOT EXISTS public.divisions
(
    divisionid serial,
    divtype character varying(20) NOT NULL,
    PRIMARY KEY (divisionid),
    UNIQUE (divtype)
);

CREATE TABLE IF NOT EXISTS public.divisionlocations
(
    locationid serial,
    divisionid serial,
    divstreet character varying(20),
    divzip character varying(10),
    divisionphome character varying(20),
    PRIMARY KEY (locationid)
);

CREATE TABLE IF NOT EXISTS public.jobdescriptions
(
    jobdesid serial,
    jobtitleid serial,
    divisionid serial,
    description text,
    PRIMARY KEY (jobdesid)
);

CREATE TABLE IF NOT EXISTS public.employeedetails
(
    emp_id serial,
    employeeid serial,
    ssn character varying(20) NOT NULL,
    departmentid serial,
    jobtitleid serial,
    divisionid serial,
    salary numeric NOT NULL,
    PRIMARY KEY (emp_id)
);

ALTER TABLE IF EXISTS public.divisionlocations
    ADD CONSTRAINT "divisionid link" FOREIGN KEY (divisionid)
    REFERENCES public.divisions (divisionid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.jobdescriptions
    ADD CONSTRAINT "jobtitleid link" FOREIGN KEY (jobtitleid)
    REFERENCES public.jobtitles (jobtitleid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.jobdescriptions
    ADD CONSTRAINT "divisionid link" FOREIGN KEY (divisionid)
    REFERENCES public.divisions (divisionid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employeedetails
    ADD CONSTRAINT "departmentid link" FOREIGN KEY (departmentid)
    REFERENCES public.departments (departmentid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employeedetails
    ADD CONSTRAINT "jobtitle link" FOREIGN KEY (jobtitleid)
    REFERENCES public.jobtitles (jobtitleid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employeedetails
    ADD CONSTRAINT "divisionid link" FOREIGN KEY (divisionid)
    REFERENCES public.divisions (divisionid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employeedetails
    ADD CONSTRAINT "ssn link" FOREIGN KEY (ssn)
    REFERENCES public.personaldetails (ssn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.employeedetails
    ADD CONSTRAINT check_positive_salary CHECK (salary > 0);

END;